### ISSUE TITLE
productChildren names display as null

### ISSUE THREAD

**Issue by Lex50** [yireo/Yireo_GoogleTagManager#102]
productChildren name appears as null for configurable product types on a clean install of Magento 1.9.4.1 with Yireo GoogleTagManager 1.5.2.

<img width="1340" alt="Screenshot 2019-04-05 at 11 50 59" src="https://user-images.githubusercontent.com/768541/55623273-6c982080-579a-11e9-836f-48e4390dcbda.png">

**Comment by jissereitsma** [comment]
In a previous Pull Request by a third party contributor, support for Configurable Products was added, but the name and the price was still missing. This has now been added in the latest release.
