### ISSUE TITLE
Unify Config Reading

### ISSUE THREAD

**Issue by sprankhub** [yireo/Yireo_GoogleTagManager#14]
You have quite similar methods for reading the config in `Yireo_GoogleTagManager_Helper_Data` as well as in `Yireo_GoogleTagManager_Block_Default`. This should be unified. I suggest keeping it in the helper and call the helper methods from the block.

**Comment by yireo** [comment]
Sigh, legacy code. Good point. I will look into this soon (but am busy with too many things at this moment) and will leave this issue open until it is fixed.

**Comment by yireo** [comment]
Done
