### ISSUE TITLE
PHP Strict Error Notice

### ISSUE THREAD

**Issue by eporsche** [yireo/Yireo_GoogleTagManager#16]
Here is the Error Log I get.

ERR (3): Strict Notice: Declaration of Yireo_GoogleTagManager_Block_Default::getHelper() should be compatible with Mage_Core_Block_Abstract::getHelper($type) in /***/app/code/community/Yireo/GoogleTagManager/Block/Default.php on line 126

I am on Magento Version 1.9.2.3 and GoogleTagManager Version 1.3.7

**Comment by yireo** [comment]
I'm not sure how this was not detected by us yet, while we run Magento in strict mode on all development sites. Anyway, a fix is now provided in version 1.3.9.
