### ISSUE TITLE
Invalid block type issue

### ISSUE THREAD

**Issue by eporsche** [yireo/Yireo_GoogleTagManager#17]
On the master branch I got errors and white pages in the frontend due to "invalid block" messages, like:

exception 'Mage_Core_Exception' with message 'Ungültiger Blocktyp: Mage_Googletagmanager_Block_Custom' 

There seems to be a naming issue, since it should be: 'Yireo_Googletagmanager_Block_Custom'

I am on Magento Version 1.9.2.3 and GoogleTagManager Version "master"

**Comment by yireo** [comment]
Thanks for the pointer. However, this is not a bug in our extension, but most likely a caching issue in your own environment. If you want us to provide support for that, please contact us via info@yireo.com. GitHub is only used by us to provide an interface for coding issues. This is not a coding issue.
