### ISSUE TITLE
satis.yireo.com malfunctioning? 

### ISSUE THREAD

**Issue by jonasvanderhaegen** [yireo/Yireo_GoogleTagManager#19]
Hoi Jisse :D 

Trying to composer update but I'm getting 
Your configuration does not allow connections to http://satis.yireo.com/packages.json. See https://getcomposer.org/doc/06-config.md#secure-http for details.  

with https-version ->
The "https://satis.yireo.com/packages.json" file could not be downloaded: Peer certificate CN=`www.yireo.com' did not match expected CN=`satis.yireo.com'  

The website's certificate needs to have a look.

For now I can go on with config "secure-http": false.

Much much thanks for all the very valuable information!
:+1:

**Comment by yireo** [comment]
Thanks for noticing. We have now added a HTTPS version of the site, so secure connections should work.
