### ISSUE TITLE
Wrong Sort Order On Category Pages

### ISSUE THREAD

**Issue by sprankhub** [yireo/Yireo_GoogleTagManager#24]
If the config value `googletagmanager/settings/category_products` is set to a value greater than zero, the sort order on category pages is wrong. E.g. if you sort by price, it does not work at all.

**Comment by jissereitsma** [comment]
Is this the same issue as in the PR https://github.com/yireo/Yireo_GoogleTagManager/pull/23 ?

**Comment by sprankhub** [comment]
No, #23 simply solved a (possible) SQL error. The sort order on category pages is still broken. At least in a shop, where I use this extension. Could not check on a clean install yet. Could you check? Thanks!

**Comment by jissereitsma** [comment]
Version 1.3.19 should fix this now

**Comment by sprankhub** [comment]
Thanks. Seems to work if I explicitely change the sorting. But if I change the sorting to "price" and open another category page (so no sort order is set in the URL), the default sorting (price) is not applied.

**Comment by jissereitsma** [comment]
Confirmed. The earlier fix was not including the stored session values yet. Now it does, plus some refactoring. Will release after inspecting #26  as well.

**Comment by sprankhub** [comment]
Seems to be fixed for me now. Thanks!
