### ISSUE TITLE
Wrong Sort Order On Tag Pages

### ISSUE THREAD

**Issue by sprankhub** [yireo/Yireo_GoogleTagManager#26]
See #24 - the same applies to tag pages.

**Comment by jissereitsma** [comment]
After the other fix, this seems to have fixed this issue for me as well. Will release now.

**Comment by sprankhub** [comment]
I still have the same issue on tag pages. Make sure to set `googletagmanager/settings/category_products` greater than zero. The issue is the search script. If I disable it, everything works again. I guess you have to apply your fixes from `Yireo_GoogleTagManager_Block_Category` also to `Yireo_GoogleTagManager_Block_Search`. Any idea when you can have a look at it? Thanks!

**Comment by sprankhub** [comment]
"Tag pages" may be wrong. Please (also) check catalogsearch result pages :)

**Comment by jissereitsma** [comment]
Actually the tag pages were not including any products so far. This is added now in the latest release which also fixes the sorting issue on catalogsearch results.
