### ISSUE TITLE
Javascript syntax error in cart and checkout when product has `"` in its name

### ISSUE THREAD

**Issue by dotboris** [yireo/Yireo_GoogleTagManager#40]
When you have a product with a double quote (`"`) in its name, the JSON generated by the module produces a javascript syntax error.

## Steps to reproduce

1. Create a product with a double quote in its name
2. Make sure that the product shows up in the frontend
3. Add the product to your cart
4. Open your cart
5. Look at the console

**Comment by jissereitsma** [comment]
Thanks for reporting this. This is now fixed in git and it will be included in the next release of the module: https://github.com/yireo/Yireo_GoogleTagManager/commit/d510ef5d7e8fe4c42a31b85b79ec96ca571b2989

**Comment by dotboris** [comment]
I have tested the new changes on my end and they work like a charm. Thanks a bunch.

By the way. Do you have an ETA for the new release?
