### ISSUE TITLE
Sort order when changed with XML layout update

### ISSUE THREAD

**Issue by judaschwartz** [yireo/Yireo_GoogleTagManager#50]
The sort order on page load does not reflect the xml updates i have added on page load (when i use the toolbar to set the sort order it works)

		<reference name="search_result_list">
			<action method="setDefaultDirection"><dir>desc</dir></action>
			<action method="setDefaultOrder"><string>arrival_date</string></action>
		</reference>
		<reference name="product_list_toolbar">
			<action method="setDefaultDirection"><dir>desc</dir></action>
			<action method="setDefaultOrder"><string>arrival_date</string></action>
		</reference>

**Comment by jissereitsma** [comment]
Isn't this a duplicate of the other issues already discussing problems with sort orders?
