### ISSUE TITLE
No SKU and brand added "twice" in product data layer

### ISSUE THREAD

**Issue by mikebranderhorst** [yireo/Yireo_GoogleTagManager#53]
https://github.com/yireo/Yireo_GoogleTagManager/blame/master/source/app/design/frontend/base/default/template/googletagmanager/data/product.phtml#L69
https://github.com/yireo/Yireo_GoogleTagManager/blame/master/source/app/design/frontend/base/default/template/googletagmanager/data/product.phtml#L71

The product dataLayer is missing the SKU and brand is added twice in the productData array.

**Comment by jissereitsma** [comment]
Thanks. This is a PR I accepted a long time ago, did not properly check and it seems to have a lot of weird stuff. It is fixed now.
