### ISSUE TITLE
Disable By Default?

### ISSUE THREAD

**Issue by sprankhub** [yireo/Yireo_GoogleTagManager#59]
Shouldn't this be disabled by default? The container ID is missing anyway, so there is no advantage in enabling it by default.

**Comment by grantkemp** [comment]
100% it should be

**Comment by jissereitsma** [comment]
I'm not sure if this would have been the fix, but aside from a configuration flag **Enabled** which is `false` by default, there now is also a check whether the GTM ID is actually supplied or not: https://github.com/yireo/Yireo_GoogleTagManager/commit/bc3b621a740a340766ae41584407b9f3e2590d05
