### ISSUE TITLE
Conversion Value should be prefixed with standard currency.

### ISSUE THREAD

**Issue by gety9** [yireo/Yireo_GoogleTagManager#63]
Thank you for the extension, it's very helpful!

It's minor thing, but might be worth looking into.

Google Tag Assistant shows suggestion:
"Conversion Value should be prefixed with standard currency."

![image](https://puu.sh/xteOM/b4e8576a69.png)

**Comment by jissereitsma** [comment]
That's strange - I don't get this suggestion anywhere in the sites I manage. And it is kind of defying the GTM fields also: The `transactionTotal` would seem to be the "Conversion Value" that Google refers to, but the GTM manual is strict in also mentioning that this number should not be prefixed with any currency and instead the `transactionCurrency` should be filled in (`USD` in your case) - which is done in our extension. I'm not sure what to modify where. Do you have suggestions in the form of a PR?

**Comment by gety9** [comment]
Thank you for you reply.

Could you explain what's the PR is? and i will try to get it.
Extension works great, this suggestion is not causing any issues.

The question that might be related - what version of source one should use?
The current master and 1.4.3 release are a bit different:
![image](https://puu.sh/xtHWy/dfc0b3bb7f.png)
![image](https://puu.sh/xtHYb/7bfb08db87.png)
![image](https://puu.sh/xtHYL/b2e81e7444.png)

**Comment by gety9** [comment]
jissereitsma, could you comment on the differences between current master and 1.4.3 release? Which one should be used?

**Comment by jissereitsma** [comment]
The official release is the release 1.4.3. If you want to use changes that are not yet released officially but are there in development, you can use the current master. Please note that if you want to join discussions on GitHub, it requires you to familiarize yourself with what GitHub is (current master, releases, PRs). I would personally not want to disturb others with this, when Google and GitHub manuals already provide this answer.
