### ISSUE TITLE
Two fields for settings?

### ISSUE THREAD

**Issue by grantkemp** [yireo/Yireo_GoogleTagManager#66]
For some reason we have two settings showing up in our module.  

The top one is for the tag manager module  What does the bottom one do?

![image](https://user-images.githubusercontent.com/751115/30216077-bea5a3d0-94a9-11e7-9dd6-e4e66ff48552.png)

**Comment by jissereitsma** [comment]
Thanks for posting. I don't know. Only the top 3 fields belong to our extension: https://github.com/yireo/Yireo_GoogleTagManager/blob/master/source/app/code/community/Yireo/GoogleTagManager/etc/system.xml

**Comment by grantkemp** [comment]
Thanks for the quick response @jissereitsma  - I suspect their might be an older version of the module in the code base somewhere

**Comment by jissereitsma** [comment]
There can only be 1 file with the name I mentioned in my account. So I'm not sure if it could be possible that the code base contains another `config.xml` in our module. Perhaps the configuration is related to the Magento core or another module?
