### ISSUE TITLE
What does transactionProducts ID stands for?

### ISSUE THREAD

**Issue by gety9** [yireo/Yireo_GoogleTagManager#69]
In our magento store we use bundle products. (all orders are placed though bundles)

In transactionProducts array sku and name are shown correctly. However ID is always increasing. So it's not product ID that one might logically expect.

Just placed 4 orders for same product with same quantity and got transactionProducts ID as 58, 60, 62, 64.

**Comment by jissereitsma** [comment]
In the quote output, the ID refers to `$product->getId()`. In the order output, the ID referred to the `$item->getId()` so the order item, I trust you noticed this as well. The following fix adds the product ID instead, which makes more sense. https://github.com/yireo/Yireo_GoogleTagManager/commit/17e8df16f7de337b48528bcb8239a4c6a6355e5c
