### ISSUE TITLE
Not working on front end (back end works fine)

### ISSUE THREAD

**Issue by marfal** [yireo/Yireo_GoogleTagManager#72]
Hi,

I tried installation thorough modman with symlinks and the following error is reported by magento:

2017-10-28T20:29:17+00:00 CRIT (2): Not valid template file:frontend/base/default/template/googletagmanager/head.phtml
2017-10-28T20:29:17+00:00 CRIT (2): Not valid template file:frontend/base/default/template/googletagmanager/noscript.phtml
2017-10-28T20:29:19+00:00 CRIT (2): Not valid template file:frontend/base/default/template/googletagmanager/data.phtml

Google Tag Manager is of course not working on the front end.

**Comment by jissereitsma** [comment]
I don't think this is an issue with our extension. We are using `modman` with this extension without issues. Do you have installed other extensions with templates via `modman` already?

**Comment by marfal** [comment]
Hi,

Thank you for getting back to me so quick. I did use modman before, although I do not claim to be an expert in it. The extension seems to be working just fine when deployed using a local copy method:

`modman deploy Yireo_GoogleTagManager --force --copy`

But when I try to use sym-link method, it appears to be having some issues entering into a circular loop.
```
[~]# modman update Yireo_GoogleTagManager
Already up-to-date.
find: Symbolic link `./foobar' is part of a loop in the directory hierarchy; we have already visited the directory to which it points.
find: Symbolic link `./www' is part of a loop in the directory hierarchy; we have already visited the directory to which it points.
Applied: source/app/code/community/Yireo/GoogleTagManager  app/code/community/Yireo/GoogleTagManager
Applied: source/app/etc/modules/Yireo_GoogleTagManager.xml  app/etc/modules/Yireo_GoogleTagManager.xml
Applied: source/app/design/frontend/base/default/layout/googletagmanager.xml  app/design/frontend/base/default/layout/googletagmanager.xml
Applied: source/app/design/frontend/base/default/template/googletagmanager  app/design/frontend/base/default/template/googletagmanager
Update of Yireo_GoogleTagManager complete.

```
After such deployment back end works fine, but some front end template files are not referenced correctly. Anyways I used the --copy method and the plugin looks great. Thank you for sharing it! 👍

**Comment by jissereitsma** [comment]
For reference: https://github.com/colinmollenhour/modman/issues/125
