### ISSUE TITLE
Gets manufacturer integer code instead textual value

### ISSUE THREAD

**Issue by cheprasovstas** [yireo/Yireo_GoogleTagManager#73]
https://github.com/yireo/Yireo_GoogleTagManager/blob/809bbc9a1643ab5e3e61c2cc540b2c474072852b/source/app/design/frontend/base/default/template/googletagmanager/data/product.phtml#L72

Proposed line
'brand' => $this->quoteEscape($product->getAttributeText('manufacturer')),

**Comment by jissereitsma** [comment]
Simply add a Pull Request for this. It is simple and effective.
