### ISSUE TITLE
Manual install (Method 2) doesn't work?

### ISSUE THREAD

**Issue by ghost** [yireo/Yireo_GoogleTagManager#74]
I had to install using FTP using installation method 2. Cleared the cache, including in my browser. Logged in and out. Still nothing. Seems the addon has done nothing and hasn't installed.

**Comment by jissereitsma** [comment]
Can you confirm that there is a file `app/etc/module/Yireo_GoogleTagManager.xml` and that the module is listed and enabled in the "Advanced > Disable modules output" section of the configuration?

**Comment by ghost** [comment]
Hi, thanks for answering so quickly. No I don't see the XML file.

**Comment by jissereitsma** [comment]
Then you have not uploaded the files in the right location.

**Comment by ghost** [comment]
Sorry, I can see it. My apologies. But I can't see the module listed.

**Comment by jissereitsma** [comment]
I don't understand. If you want people to help you voluntarily on a Saturday without asking money for it, please got the extra length of explaining in detail what problems you are facing. The less information you provide, the more I wonder why I should help out. Hundreds of users are using the module just fine and experience 0 issues with installing things. So you need to realize that there is nothing wrong with this extension. It is just that you lack the knowledge so far to install a module. That's fine and you can call for help. But just make sure you do everything in your power to help the other side help you.

**Comment by ghost** [comment]
I have downloaded, unzipped and installed the files in the correct directories. The XML file is where you say it should be. I go to the Advanced -> Disabled Modules Output section of the Configuration (after clearing the cache and logging out then back in) and the module isn't there. This on Magento 1.9.3.6.
So my 9 years in web dev isn't enough to get this perfect plugin to install. Please help.

**Comment by jissereitsma** [comment]
So earlier you mentioned the XML file was not there. Now it is. Something has changed. If this was due to steps that were missing, could you confirm that after the XML was suddenly there, you have flushed the cache and logged out/in again?

**Comment by ghost** [comment]
The XML was there, I was mistakingly looking one directory above (/etc/ instead of /etc/module). I didn't upload anything new. I just flushed everything again and logged in and out but it hasn't helped.
I think I'll delete everything and start the process again.
