### ISSUE TITLE
A formated price is invalid in number_format, must be float

### ISSUE THREAD

**Issue by mikebranderhorst** [yireo/Yireo_GoogleTagManager#78]
Warning: number_format() expects parameter 1 to be float, string given  in app/design/frontend/base/default/template/googletagmanager/data/product.phtml on line 70

$this->getModuleHelper()->getProductPrice($product)

Returns: ```<span class="price">€ 123,00</span>```

It should be float: 123.00

**Comment by jissereitsma** [comment]
Could you create a Pull Request for this? It actually offers less work than raising an issue ....

**Comment by jissereitsma** [comment]
https://github.com/yireo/Yireo_GoogleTagManager/commit/3c1c9b06e924e24424e6bdc322a118f30afac444
