### ISSUE TITLE
Price has four decimals, make it two

### ISSUE THREAD

**Issue by mikebranderhorst** [yireo/Yireo_GoogleTagManager#79]
app/code/community/Yireo/GoogleTagManager/Block/Quote.php:84
app/code/community/Yireo/GoogleTagManager/Block/Order.php:83

'price' => $price,

'price' => number_format($price, 2),

app/code/local/Yireo/GoogleTagManager/Observer/ProductListData.php:125

$data['price'] = $price;

$data['price'] = number_format($price, 2);

**Comment by jissereitsma** [comment]
Could you create a Pull Request for this? Adding an issue that offers an entire solution, is actually still more work than a simple PR ...

**Comment by jissereitsma** [comment]
https://github.com/yireo/Yireo_GoogleTagManager/commit/616868a39b95dd3e92c2516b6babe14fae238335
