### ISSUE TITLE
Configurable Items added to data layer on order

### ISSUE THREAD

**Issue by simonrl** [yireo/Yireo_GoogleTagManager#9]
When ordering a configurable product (for example, T-Shirt size M), both products (configurable & simple) are added to the data layer in the success page which gives wrong ecommerce tracking data in GA. I am using the latest version (installed about 30 minutes ago).

The fix is simple: change Block/Order.php line 21 to:

``` php
if( $item->getParentItemId() ) {
    continue; 
}
```

**Comment by yireo** [comment]
Thanks. This sounds like a solid solution. Could you create a Pull Request for this (which is actually what most of the magic of GitHub is about)? Then I'll include it right away.

**Comment by simonrl** [comment]
done
https://github.com/yireo/Yireo_GoogleTagManager/pull/10

**Comment by yireo** [comment]
Awesome. PR is merged. This Monday we'll pick up on a new release as well for MagentoConnect. Thanks again!
