### ISSUE TITLE
Tried to install this, site now directs to white screen

### ISSUE THREAD

**Issue by RichColeman** [yireo/Yireo_GoogleTagManager#98]
Hello, a client was trying to install GTM onto their Magento site and I tried to upload this extension via upload of the zip. I wasn't sure if an error occurred or not, but the site no longer renders and I'm getting a white screen. Any ideas?

**Comment by jissereitsma** [comment]
I think it is impossible to troubleshoot a white screen, because it is invented to hide the information from the web. Instead, the white screen tells you that there is an Internal Server Error. Could you contact the system administrator to find out the actual error that is causing the white screen? Without an error, no one is able to say anything.

**Comment by RichColeman** [comment]
Thanks for the response. I was able to get this fixed! No issue with your plugin.

**Comment by jissereitsma** [comment]
Could you maybe share what the issue was after all? Because the next time this question pops up, it might be helpful to others if the answer is already there.

**Comment by RichColeman** [comment]
Yes my apologies! I am extremely new to Magento so I tried a number of
troubleshooting steps found online, including clearing var/cache in ssh in
terminal. This did not do the trick. However, once I removed
"maintenance.flag" from the root of the folder, the site was able to load
successfully!

I'm wondering if uploading the GTM extension zip caused an error in my
client's template and created the maintenance flag file?

**Comment by jissereitsma** [comment]
No, the `maintenance.flag` has nothing to do with uploading extension files via SSH or FTP. However, if you stop an upgrade process within the Magento Downloader application of your site, this file is there. It is documented on the Magento fora as well. Glad to hear it was solved.
